export const permissionCatalog = [
  { key: 'dashboard.view', name: 'View dashboard', module: 'dashboard' },
  { key: 'people.view', name: 'View people', module: 'people' },
  { key: 'people.create', name: 'Create people', module: 'people' },
  { key: 'people.update', name: 'Update people', module: 'people' },
  { key: 'people.delete', name: 'Delete/archive people', module: 'people' },
  { key: 'people.import', name: 'Import people', module: 'people' },
  { key: 'people.bulkDelete', name: 'Bulk delete people', module: 'people' },
  { key: 'people.export', name: 'Export people', module: 'people' },
  { key: 'people.viewBirthdays', name: 'View birthdays', module: 'people' },
  { key: 'people.sendBirthdaySms', name: 'Send birthday SMS', module: 'people' },
  { key: 'departments.view', name: 'View departments', module: 'departments' },
  { key: 'departments.create', name: 'Create departments', module: 'departments' },
  { key: 'departments.update', name: 'Update departments', module: 'departments' },
  { key: 'departments.delete', name: 'Delete departments', module: 'departments' },
  { key: 'departments.addMember', name: 'Add department members', module: 'departments' },
  { key: 'departments.removeMember', name: 'Remove department members', module: 'departments' },
  { key: 'departments.transferMember', name: 'Transfer department members', module: 'departments' },
  { key: 'departments.assignHead', name: 'Assign department heads', module: 'departments' },
  { key: 'departments.manageOwnDepartment', name: 'Manage own department', module: 'departments' },
  { key: 'welfare.view', name: 'View welfare', module: 'welfare' },
  { key: 'welfare.viewDashboard', name: 'View welfare dashboard', module: 'welfare' },
  { key: 'welfare.recordPayment', name: 'Record welfare payments', module: 'welfare' },
  { key: 'welfare.updatePayment', name: 'Update welfare payments', module: 'welfare' },
  { key: 'welfare.deletePayment', name: 'Delete welfare payments', module: 'welfare' },
  { key: 'welfare.export', name: 'Export welfare', module: 'welfare' },
  { key: 'attendance.view', name: 'View attendance', module: 'attendance' },
  { key: 'attendance.record', name: 'Record attendance', module: 'attendance' },
  { key: 'attendance.update', name: 'Update attendance', module: 'attendance' },
  { key: 'attendance.delete', name: 'Delete attendance', module: 'attendance' },
  { key: 'attendance.createSection', name: 'Create attendance sections', module: 'attendance' },
  { key: 'attendance.viewHistory', name: 'View attendance history', module: 'attendance' },
  { key: 'events.view', name: 'View events', module: 'events' },
  { key: 'events.create', name: 'Create events', module: 'events' },
  { key: 'events.update', name: 'Update events', module: 'events' },
  { key: 'events.cancel', name: 'Cancel events', module: 'events' },
  { key: 'events.delete', name: 'Delete events', module: 'events' },
  { key: 'events.recordAttendance', name: 'Record event attendance', module: 'events' },
  { key: 'expenses.view', name: 'View expenses', module: 'expenses' },
  { key: 'expenses.create', name: 'Create expenses', module: 'expenses' },
  { key: 'expenses.createForDepartment', name: 'Create department expenses', module: 'expenses' },
  { key: 'expenses.viewDepartmentExpenses', name: 'View department expenses', module: 'expenses' },
  { key: 'expenses.viewAllExpenses', name: 'View all expenses', module: 'expenses' },
  { key: 'expenses.update', name: 'Update expenses', module: 'expenses' },
  { key: 'expenses.approve', name: 'Approve expenses', module: 'expenses' },
  { key: 'expenses.reject', name: 'Reject expenses', module: 'expenses' },
  { key: 'expenses.markPaid', name: 'Mark expenses paid', module: 'expenses' },
  { key: 'expenses.delete', name: 'Delete expenses', module: 'expenses' },
  { key: 'expenses.export', name: 'Export expenses', module: 'expenses' },
  { key: 'funds.view', name: 'View funds', module: 'funds' },
  { key: 'funds.create', name: 'Create funds', module: 'funds' },
  { key: 'funds.update', name: 'Update funds', module: 'funds' },
  { key: 'funds.recordPayment', name: 'Record fund payments', module: 'funds' },
  { key: 'funds.delete', name: 'Delete funds', module: 'funds' },
  { key: 'funds.export', name: 'Export funds', module: 'funds' },
  { key: 'finance.view', name: 'View finance', module: 'finance' },
  { key: 'finance.history.view', name: 'View finance history', module: 'finance' },
  { key: 'finance.export', name: 'Export finance', module: 'finance' },
  { key: 'reports.read', name: 'View reports', module: 'reports' },
  { key: 'communications.view', name: 'View communications', module: 'communications' },
  { key: 'communications.sendSms', name: 'Send SMS', module: 'communications' },
  { key: 'communications.sendBirthdaySms', name: 'Send birthday SMS', module: 'communications' },
  { key: 'communications.sendAnnouncement', name: 'Send announcements', module: 'communications' },
  { key: 'communications.viewHistory', name: 'View communication history', module: 'communications' },
  { key: 'settings.view', name: 'View settings', module: 'settings' },
  { key: 'settings.updateProfile', name: 'Update profile settings', module: 'settings' },
  { key: 'settings.updateChurchProfile', name: 'Update church profile', module: 'settings' },
  { key: 'settings.updateFinance', name: 'Update finance settings', module: 'settings' },
  { key: 'settings.updateAttendance', name: 'Update attendance settings', module: 'settings' },
  { key: 'settings.updateDepartments', name: 'Update department settings', module: 'settings' },
  { key: 'settings.updateAppearance', name: 'Update appearance settings', module: 'settings' },
  { key: 'settings.updateCommunications', name: 'Update communication settings', module: 'settings' },
  { key: 'users.view', name: 'View platform users', module: 'users' },
  { key: 'users.create', name: 'Create platform users', module: 'users' },
  { key: 'users.update', name: 'Update platform users', module: 'users' },
  { key: 'users.deactivate', name: 'Deactivate users', module: 'users' },
  { key: 'users.invite', name: 'Invite users', module: 'users' },
  { key: 'users.resetPassword', name: 'Reset user passwords', module: 'users' },
  { key: 'roles.view', name: 'View roles', module: 'users' },
  { key: 'roles.create', name: 'Create roles', module: 'users' },
  { key: 'roles.update', name: 'Update roles', module: 'users' },
  { key: 'roles.delete', name: 'Delete roles', module: 'users' },
  { key: 'roles.assign', name: 'Assign roles', module: 'users' },
  { key: 'permissions.override', name: 'Override permissions', module: 'users' },
  { key: 'auditLogs.view', name: 'View audit logs', module: 'auditLogs' },
  { key: 'auditLogs.viewDetails', name: 'View audit log details', module: 'auditLogs' },
  { key: 'auditLogs.export', name: 'Export audit logs', module: 'auditLogs' },
] as const;

export const permissions = permissionCatalog.map((permission) => permission.key);
export type PermissionKey = (typeof permissions)[number];

export const defaultRoles = [
  'Super Admin',
  'Pastor',
  'Church Administrator',
  'First Lady',
  'Head of Department',
  'Finance Officer',
  'Welfare Officer',
  'Viewer',
] as const;

export type DefaultRoleName = (typeof defaultRoles)[number];

export const removedRoles = [
  'Attendance Officer',
  'Attendance Officer / Ushers',
  'Events Coordinator',
  'Auditor',
  'Group Leader',
  'Member',
] as const;

export const defaultRolePermissions: Record<DefaultRoleName, string[]> = {
  'Super Admin': [...permissions],
  Pastor: [
    'dashboard.view',
    'people.view',
    'people.viewBirthdays',
    'departments.view',
    'attendance.view',
    'welfare.view',
    'welfare.viewDashboard',
    'finance.view',
    'events.view',
    'reports.read',
    'auditLogs.view',
  ],
  'Church Administrator': [
    'dashboard.view',
    'people.view',
    'people.create',
    'people.update',
    'people.import',
    'people.export',
    'people.viewBirthdays',
    'departments.view',
    'departments.create',
    'departments.update',
    'departments.addMember',
    'departments.removeMember',
    'departments.transferMember',
    'departments.assignHead',
    'attendance.view',
    'attendance.record',
    'attendance.update',
    'attendance.viewHistory',
    'events.view',
    'events.create',
    'events.update',
    'events.cancel',
    'communications.view',
    'communications.sendSms',
    'communications.sendBirthdaySms',
    'communications.sendAnnouncement',
    'communications.viewHistory',
    'settings.view',
    'settings.updateProfile',
    'settings.updateChurchProfile',
    'settings.updateCommunications',
    'users.view',
    'users.create',
    'users.update',
    'roles.view',
    'roles.assign',
  ],
  'First Lady': [
    'dashboard.view',
    'people.view',
    'people.viewBirthdays',
    'people.sendBirthdaySms',
    'welfare.view',
    'welfare.viewDashboard',
    'events.view',
    'communications.view',
    'communications.sendSms',
    'communications.sendBirthdaySms',
    'departments.view',
  ],
  'Head of Department': [
    'dashboard.view',
    'people.view',
    'departments.view',
    'departments.manageOwnDepartment',
    'expenses.createForDepartment',
    'expenses.viewDepartmentExpenses',
    'events.view',
  ],
  'Finance Officer': [
    'dashboard.view',
    'finance.view',
    'finance.history.view',
    'expenses.view',
    'expenses.create',
    'expenses.update',
    'expenses.markPaid',
    'expenses.export',
    'funds.view',
    'funds.create',
    'funds.update',
    'funds.recordPayment',
    'funds.export',
  ],
  'Welfare Officer': [
    'dashboard.view',
    'people.view',
    'welfare.view',
    'welfare.viewDashboard',
    'welfare.recordPayment',
    'welfare.updatePayment',
    'welfare.export',
  ],
  Viewer: [
    'dashboard.view',
    'people.view',
    'departments.view',
    'events.view',
  ],
};
